# Generated by Django 5.0.7 on 2024-08-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneBcells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('avg_log2fc_1', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('p_val_adj_1', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('avg_log2fc_2', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('p_val_adj_2', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('avg_log2fc_3', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('p_val_adj_3', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('avg_log2fc_4', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('p_val_adj_4', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('avg_log2fc_5', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('p_val_adj_5', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('avg_log2fc_6', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('p_val_adj_6', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('avg_log2fc_7', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('p_val_adj_7', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
            ],
            options={
                'db_table': 'gene_bcells',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GeneCD4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('avg_log2fc_1', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('p_val_adj_1', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('avg_log2fc_2', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('p_val_adj_2', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('avg_log2fc_3', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('p_val_adj_3', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('avg_log2fc_4', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('p_val_adj_4', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('avg_log2fc_5', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('p_val_adj_5', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('avg_log2fc_6', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('p_val_adj_6', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('avg_log2fc_7', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('p_val_adj_7', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
            ],
            options={
                'db_table': 'gene_cd4',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GeneCD8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('avg_log2fc_1', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('p_val_adj_1', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('avg_log2fc_2', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('p_val_adj_2', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('avg_log2fc_3', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('p_val_adj_3', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('avg_log2fc_4', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('p_val_adj_4', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('avg_log2fc_5', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('p_val_adj_5', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('avg_log2fc_6', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('p_val_adj_6', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('avg_log2fc_7', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('p_val_adj_7', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
            ],
            options={
                'db_table': 'gene_cd8',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GeneMonocytes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('avg_log2fc_1', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('p_val_adj_1', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('avg_log2fc_2', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('p_val_adj_2', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('avg_log2fc_3', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('p_val_adj_3', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('avg_log2fc_4', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('p_val_adj_4', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('avg_log2fc_5', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('p_val_adj_5', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('avg_log2fc_6', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('p_val_adj_6', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('avg_log2fc_7', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('p_val_adj_7', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
            ],
            options={
                'db_table': 'gene_monocytes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GeneNkcells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('avg_log2fc_1', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('p_val_adj_1', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('avg_log2fc_2', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('p_val_adj_2', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('avg_log2fc_3', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('p_val_adj_3', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('avg_log2fc_4', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('p_val_adj_4', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('avg_log2fc_5', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('p_val_adj_5', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('avg_log2fc_6', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('p_val_adj_6', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('avg_log2fc_7', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
                ('p_val_adj_7', models.DecimalField(blank=True, decimal_places=200, max_digits=200, null=True)),
            ],
            options={
                'db_table': 'gene_nkcells',
                'managed': False,
            },
        ),
    ]
